import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Link from "next/link"

export default  function Home({ data, countries, country }) {

  console.log(countries);

  return (
    <div className={styles.container}>
      <Head>
        <title>Covid 19 Api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className={styles.date}>
      <p>Date: {data.Date.split("T")[0]} </p>
    </div>

    <div className={styles.countries}>
    {countries.map(country => (
      <Link href={country.Country.toLowerCase()}>
      <div className={styles.country} key={country.ID}>
        <h2>{country.Country}</h2>
        <img src={`https://flagcdn.com/${country.CountryCode.toLowerCase()}.svg`} />
        <p>Deaths: {country.TotalDeaths}</p>
        <p>Confirmed: {country.TotalConfirmed}</p>
        <p>Recovered: {country.TotalRecovered}</p>
      </div>
      </Link>
    ))}
    </div>
    </div>
  );
};

export async function getServerSideProps(context) {

  const res = await fetch("https://api.covid19api.com/summary");
  const data = await res.json();

  const countries = await data.Countries.filter(country => country.TotalConfirmed > 100000);
  countries.sort((a,b) => a.TotalConfirmed > b.TotalConfirmed ? -1 : 1);

  return {
    props: { data, countries } // will be passed to the page component as props
  }
}